name: 00. Test AWS OIDC

on:
  workflow_dispatch:   # chạy thủ công từ GitHub UI

jobs:
  aws-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # cần cho OIDC
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::491085416582:role/GitHubActions-Role # get on AWS IAM console
          aws-region: us-east-2

      - name: Verify identity
        run: aws sts get-caller-identity
