name: Install Node Exporter

on:
  workflow_dispatch:

jobs:
  install-node-exporter:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # cần cho OIDC
      contents: read


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::491085416582:role/GitHubActions-Role # get on AWS IAM console
          aws-region: us-east-2


      - name: Download Terraform state
        run: |
          aws s3 cp s3://terraform-state-justin-udacity/terraform/terraform.tfstate terraform.tfstate

      - name: Get EC2 Public IP
        id: getip
        run: |
          IP=$(jq -r '.resources[] | select(.type=="aws_instance") | .instances[0].attributes.public_ip' terraform.tfstate)
          echo "EC2_IP=$IP" >> $GITHUB_ENV        


      - name: Install Node Exporter via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }} # hoặc password nếu bạn chọn
          script: |
            wget https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
            tar xvf node_exporter-1.8.2.linux-amd64.tar.gz
            sudo mv node_exporter-1.8.2.linux-amd64/node_exporter /usr/local/bin/

            sudo useradd --no-create-home --shell /bin/false node_exporter || true
            sudo chown node_exporter:node_exporter /usr/local/bin/node_exporter

            sudo tee /etc/systemd/system/node_exporter.service <<EOF
            [Unit]
            Description=Node Exporter
            Wants=network-online.target
            After=network-online.target

            [Service]
            User=node_exporter
            Group=node_exporter
            Type=simple
            ExecStart=/usr/local/bin/node_exporter

            [Install]
            WantedBy=multi-user.target
            EOF

            sudo systemctl daemon-reload
            sudo systemctl enable --now node_exporter
            sudo systemctl start node_exporter
    