name: Slack Notification

on:
    workflow_call:
    inputs:
      status:
        required: true
        type: string
      stage:
        required: true
        type: string
      environment:
        required: true
        type: string
      repository:
        required: true
        type: string
      actor:
        required: true
        type: string
      run_url:
        required: true
        type: string
      summary_file:
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Build Slack message payload
        id: build_payload
        run: |
          STATUS="${{ inputs.status }}"
          ICON=":white_check_mark:"
          COLOR="good"
          TEXT_STATUS="Success"

          if [ "$STATUS" != "success" ]; then
            ICON=":x:"
            COLOR="danger"
            TEXT_STATUS="Failed"
          fi

          # Đọc 20 dòng cuối từ summary file (nếu có)
          SUMMARY=""
          if [ -n "${{ inputs.summary_file }}" ] && [ -f "${{ inputs.summary_file }}" ]; then
            SUMMARY=$(tail -n 20 "${{ inputs.summary_file }}" | sed 's/"/\\"/g')
          else
            SUMMARY="(no summary found)"
          fi

          cat <<EOF > slack_payload.json
          {
            "text": "${ICON} *${{ inputs.stage }}* on *${{ inputs.environment }}* — *${TEXT_STATUS}*",
            "attachments": [
              {
                "color": "${COLOR}",
                "fields": [
                  { "title": "Repository", "value": "${{ inputs.repository }}", "short": true },
                  { "title": "Triggered by", "value": "${{ inputs.actor }}", "short": true },
                  { "title": "Environment", "value": "${{ inputs.environment }}", "short": true },
                  { "title": "Status", "value": "${TEXT_STATUS}", "short": true },
                  { "title": "Logs", "value": "<${{ inputs.run_url }}|View Run Details>", "short": false }
                ]
              },
              {
                "color": "#AAAAAA",
                "text": "*Last 20 lines of log:*\n\`\`\`${SUMMARY}\`\`\`"
              }
            ]
          }
          EOF

          echo "Payload built:"
          cat slack_payload.json

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload-file-path: slack_payload.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
