name: Terraform Destroy (OIDC)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'YES' to confirm destroy"
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # cần cho OIDC
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # ✅ OIDC Authentication with AWS
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::491085416582:role/GitHubActions-Role
          aws-region: us-east-2

      # ✅ Optional: require manual confirmation
      - name: Confirm destroy
        if: ${{ github.event.inputs.confirm != 'YES' }}
        run: |
          echo "❌ Destroy cancelled: please type 'YES' to confirm."
          exit 1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan-destroy

      - name: Terraform Destroy
        run: terraform apply -auto-approve tfplan-destroy
